config/routes.rb
DemoApp::Application.routes.draw do

	get '/welcome' => 'welcome#index'

	get '/welcome/action' => 'welcome#showaction'

	get '/welcome/layout' => 'welcome#showlayouts'

	get '/welcome/routing' => 'welcome#showrouting'

   root 'welcome#index'

    resources :articles

end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/models/window.rb
class Window < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	layout "articles"
	
	def index
		@articles=Article.all
	end

	def create
		@article=Article.new(params.require(:article).permit(:title, :text))
		if @article.save
			redirect_to articles_path
		else
			render "edit"
		end

	end

	def new
		@article=Article.new()
	end

	def edit
		@article=Article.find(params[:id])
	end

	def update
		@article=Article.find(params[:id])
		if @article.update(params.require(:article).permit(:title, :text))
			redirect_to articles_path
		else
			render "edit"
		end
	end

	def show
		@article=Article.find(params[:id])
	end

	def destroy
		@article=Article.find(params[:id])
		@article.destroy()
		redirect_to articles_path
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	layout "welcome"

	def Index
		render "index"
	end

	def ShowAction
		 render "showaction"
		#redirect_to welcome_path
	end

	def ShowLayouts
		render "showlayouts"
	end

	def ShowRouting
		render "showrouting"
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/edit.html.erb
<div class="well">
<%= link_to 'Back to Index', articles_path %>
</div>

<%= form_for :article, url: article_path(@article), method: :put do |f| %>
<p>
	<%= f.label :title %><br/>
	<%= f.text_field :title %>
</p>

<p>
	<%= f.label :text %><br/>
	<%= f.text_area :text %>
</p>

<p>
	<%= f.submit %>
</p>
<% end %>

app/views/articles/index.html.erb
<p>
<%= link_to 'Create a New Article', new_article_path %>
</p>
<table class="table table-bordered table-stripped">
<thead>
<tr>
<th>Title</th>
<th>Text</th>
<th></th>
<th></th>
<th></th>
</tr>
</thead>
<tbody>
<% @articles.each do |article| %>
	<tr>
		<td><%= article.title %></td>
		<td><%= article.text %></td>
		<td><%= link_to 'Show Details', article_path(article) %></td>
		<td><%= link_to 'Edit', edit_article_path(article) %></td>
		<td><%= link_to 'Delete', article_path(article), method: :delete %></td>
	</tr>
<% end %>
</tbody>
</table>

app/views/articles/new.html.erb
<% link_to("Back to Index", articles_path) %>

<%= form_for :article, url: articles_path, method: :post do |f| %>
<p>
	<%= f.label :title %><br/>
	<%= f.text_field :title %>
</p>

<p>
	<%= f.label :text %><br/>
	<%= f.text_area :text %>
</p>

<p>
	<%= f.submit %>
</p>
<% end %>

app/views/articles/show.html.erb
<div class="well">
<%= link_to 'Back to Index', articles_path %>
</div>

<p class="lead">
<div class="col-md-1">
Text :
</div>
<div class="col-md-11 well">
<%= @article.title %>
</div>
</p>
<p class="lead">
<div class="col-md-1">
Title :
</div>
<div class="col-md-11 well">
<%= @article.text %>
</div>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DemoApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/articles.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Articles Page</title>
  <%= stylesheet_link_tag    "http://netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js", "http://netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js", "data-turbolinks-track" => true %>
</head>
<body>
<div class="container">
<div class="page-header">
<h2>Articles</h2>
</div>
<div class="row">
<%= yield %>
</div>
</div>
</body>
</html>

app/views/layouts/welcome.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Welcome Page</title>
  <%= stylesheet_link_tag    "http://netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js", "http://netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js", "data-turbolinks-track" => true %>
</head>
<body>
<div class="container">
<div class="row">
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Rails</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/welcome/action">Action Controllers</a></li>
        <li class="active"><a href="/welcome/layout">Layouts and Rendering</a></li>
        <li class="active"><a href="/welcome/routing">Rails Routing</a></li>
        <li class="active"><%= link_to 'Articles', articles_path %></li>
        </ul>
        </div>
        </div>
        </nav>
</div>
<div class="row" style="margin-top:70px;margin-bottom:50px;">
<%= yield %>
</div>
</div>
</body>
</html>

app/views/welcome/index.html.erb
<%= @data %>
<h1>Welcome to Rails Application</h1>
<p class="well">Rails is a web application development framework written in the Ruby language. It is designed to make programming web applications easier by making assumptions about what every developer needs to get started. It allows you to write less code while accomplishing more than many other languages and frameworks. Experienced Rails developers also report that it makes web application development more fun.</p>


<p class="well">Rails is opinionated software. It makes the assumption that there is the "best" way to do things, and it's designed to encourage that way - and in some cases to discourage alternatives. If you learn "The Rails Way" you'll probably discover a tremendous increase in productivity. If you persist in bringing old habits from other languages to your Rails development, and trying to use patterns you learned elsewhere, you may have a less happy experience.</p>

<div class="well">
	<ul class="list-unstyled">
	<li>
		<div class="panel panel-primary">
  		<div class="panel-heading">Don't Repeat Yourself</div>
  		<div class="panel-body">
    		DRY is a principle of software development which states that "Every piece of knowledge must have a single, unambiguous, authoritative representation within a system." By not writing the same information over and over again, our code is more maintainable, more extensible, and less buggy.
  		</div>
		</div>		
	</li>
	<li>
		<div class="panel panel-primary">
  		<div class="panel-heading">Convention over Configuration</div>
  		<div class="panel-body">
    		Rails has opinions about the best way to do many things in a web application, and defaults to this set of conventions, rather than require that you specify every minutiae through endless configuration files.
  		</div>
		</div>		
	</li>
	</ul>
</div>

app/views/welcome/showaction.html.erb
<div class="well">
<h1>1 What Does a Controller Do?</h1>
<p>
	Action Controller is the C in MVC. After routing has determined which controller to use for a request, your controller is responsible for making sense of the request and producing the appropriate output. Luckily, Action Controller does most of the groundwork for you and uses smart conventions to make this as straightforward as possible.

For most conventional RESTful applications, the controller will receive the request (this is invisible to you as the developer), fetch or save data from a model and use a view to create HTML output. If your controller needs to do things a little differently, that's not a problem, this is just the most common way for a controller to work.

A controller can thus be thought of as a middle man between models and views. It makes the model data available to the view so it can display that data to the user, and it saves or updates data from the user to the model.
</p>
</div>

<div class="well">
<h1>2 Controller Naming Convention</h1>
<p>
	The naming convention of controllers in Rails favors pluralization of the last word in the controller's name, although it is not strictly required (e.g. ApplicationController). For example, ClientsController is preferable to ClientController, SiteAdminsController is preferable to SiteAdminController or SitesAdminsController, and so on.

Following this convention will allow you to use the default route generators (e.g. resources, etc) without needing to qualify each :path or :controller, and keeps URL and path helpers' usage consistent throughout your application.
</p>
</div>

app/views/welcome/showlayouts.html.erb
<div class="well">
<h1>1 Overview: How the Pieces Fit Together</h1>
<p>
	This guide focuses on the interaction between Controller and View in the Model-View-Controller triangle. As you know, the Controller is responsible for orchestrating the whole process of handling a request in Rails, though it normally hands off any heavy code to the Model. But then, when it's time to send a response back to the user, the Controller hands things off to the View. It's that handoff that is the subject of this guide.

In broad strokes, this involves deciding what should be sent as the response and calling an appropriate method to create that response. If the response is a full-blown view, Rails also does some extra work to wrap the view in a layout and possibly to pull in partial views. You'll see all of those paths later in this guide.
</div>

<div class="well">
<h1>2 Creating Responses</h1>
<p>
	From the controller's point of view, there are three ways to create an HTTP response:
	<ul>
		<li>Call render to create a full response to send back to the browser</li>
		<li>Call redirect_to to send an HTTP redirect status code to the browser</li>
		<li>Call head to create a response consisting solely of HTTP headers to send back to the browser</li>
	</ul>
</p>
</div>

app/views/welcome/showrouting.html.erb
<div class="well">
<h1>1 The Purpose of the Rails Router</h1>
<p>
	The Rails router recognizes URLs and dispatches them to a controller's action. It can also generate paths and URLs, avoiding the need to hardcode strings in your views.
</p>
</div>

<div class="well">
<h3>1.1 Connecting URLs to Code</h3>
<p>
	When your Rails application receives an incoming request for:

	GET /patients/17

	it asks the router to match it to a controller action. If the first matching route is:

	get '/patients/:id', to: 'patients#show'

	the request is dispatched to the patients controller's show action with { id: '17' } in params.
</p>
</div>

<div class="well">
<h3>1.1 Connecting URLs to Code</h3>
<p>
	When your Rails application receives an incoming request for:

	GET /patients/17

	it asks the router to match it to a controller action. If the first matching route is:

	get '/patients/:id', to: 'patients#show'

	the request is dispatched to the patients controller's show action with { id: '17' } in params.
</p>
</div>